name: Test Examples

on:
  workflow_call:
  push:

jobs:
  test-after-changing-file-names:
    uses: ./.github/workflows/Remove-Function-Name-Prefix.yml
  run-node-tests:
    runs-on: ubuntu-latest
    needs: [test-after-changing-file-names]
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: tests/integration
        run: npm install
      - name: Test the Examples
        working-directory: tests/integration
        run: npm run test:ts