name: Zip and Upload to S3 for Development

on:
  workflow_run:
    workflows: [Test Examples]
    types:
      - completed
  push:
    branches:
      - development

jobs:
  deploy-after-testing:
    uses: ./.github/workflows/Run-Tests.yml
  zip-and-upload:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: [deploy-after-testing]
    steps:
      - uses: actions/checkout@v2
      - run: mkdir zip
      - run: zip -r zip/triggers-functions-examples.zip . -x ".DS_Store" ".git/*" ".github/*" ".gitignore" "./zip/" "README.md" "backend/*" "test/*" "tools/*"
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ./zip
          destination_dir: "v1/development"